import type { Metadata } from "next";
import "./globals.css";
import Josefinsans from "./fonts/font";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Categories from "@/components/categories";

export const metadata: Metadata = {
  title: "BotBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Josefinsans.className} antialiased text-black`}
      >
        <Header/>
        <Categories />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
